name: Simple
description: Plantilla para sitios estáticos simples
# paginate: 10
baseurl: "/simple_template"
# url: "" 
# the base hostname & protocol for your site, e.g. http://example.com

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# This is to keep things tidy.
include: ['_pages']

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor